---
- name: Déploiement de l'app web
  hosts: webserver
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Installation des dépendances
      apt:
        name:
          - git
          - nginx
          - python3
          - python3-pip
        state: present

    - name: S'assurer que nginx est démarré et activé
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Cloner le repo git de l'app
      git:
        repo: "https://github.com/Denhetsu/todo-app-4emeAnnee.git"
        dest: /var/www/app
        version: dev
        force: yes

    - name: Configuration Nginx
      copy:
        dest: /etc/nginx/sites-available/app
        content: |
          server {
              listen 80;
              root /var/www/app;
              index index.html;
              server_name _;
          }
      notify: Restart nginx

    - name: Activer la config Nginx
      file:
        src: /etc/nginx/sites-available/app
        dest: /etc/nginx/sites-enabled/app
        state: link
        force: yes

    - name: Désactiver le site par défaut de Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
