name: "CI"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check-branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Vérification branche
        run: echo "La branche est bien 'dev'"